Step3-kakao-tech-campus/Team11_BE

src/main/java/com/kakao/golajuma/common/support/respnose/SliceResponse.java
무한 스크롤 시 사용할 Response 추가했습니다.
closes (#이슈번호)
=> [FEAT] 무한스크롤 시 사용할 response 추가

build.gradle, src/main/java/com/kakao/golajuma/auth/domain/helper/Encoder.java, src/main/java/com/kakao/golajuma/auth/infra/converter/UserEntityConverter.java
시큐리티 의존성을 제거합니다.
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [FIX] 시큐리티 의존성 제거

src/main/java/com/kakao/golajuma/auth/domain/exception/AuthorizationException.java, src/main/java/com/kakao/golajuma/auth/domain/token/TokenProvider.java, src/main/java/com/kakao/golajuma/auth/domain/token/TokenResolver.java, src/main/java/com/kakao/golajuma/auth/domain/token/TokenValidator.java, src/main/java/com/kakao/golajuma/auth/web/controller/AuthInterceptor.java, src/main/java/com/kakao/golajuma/auth/web/support/AuthenticationPrincipalArgumentResolver.java, src/main/java/com/kakao/golajuma/auth/web/support/AuthorizationExtractor.java, src/main/java/com/kakao/golajuma/auth/web/support/Login.java, src/main/java/com/kakao/golajuma/auth/web/support/TokenExtractor.java, src/main/java/com/kakao/golajuma/config/WebMvcConfig.java, src/main/resources/application-local-security.yml
인가 처리 구현했습니다.
*  TokenExtractor
* header값에서 토큰을 추출합니다.
* TokenValidation
* token 만료 여부를 검증합니다.
* TokenResolver
*  토큰에서 정보를 추출합니다.
* AuthenticationPrincipalArgumentResolver, Login 
* 로그인 된 사용자인지 검증합니다.
* TokenExtractor를 통해서 토큰값을 가져오고
* TokenValidation에게 토큰을 검증합니다.
* 만약, 로그인 된 사용자라면 Long userId를 반환하고 로그인 되지 않은 사용자라면 null을 반환합니다.
* interceptor를 통해서 토큰 추출하고 검증합니다.
* WebMvcConfig에서 api/auth의 경우(인증) 인터셉터(토큰 검증)부분이 필요하지 않다고 생각하여 제외하였습니다.
로그인 된 사용자 정보가 필요하면` @Login Long userId` 를 사용하면 됩니다!!
* vote(진행중인 투표) GET요청시 token값이 없어도 통과는 해야한다.
`만약 값이 있으면 userId정보는 넘겨주고, 없으면 null로 들어간다.`
* comment(만료된 투표) GET요청시 token값이 없어도 통과는 해야한다.
* comment(진행중인 투표) GET요청시 token값이 없을 때 불통과한다.
closed #32 
=> [Feat ] 인가 처리 구현 

src/test/java/com/kakao/golajuma/auth/domain/service/SaveUserServiceTest.java, src/test/java/com/kakao/golajuma/auth/domain/service/ValidEmailServiceTest.java, src/test/java/com/kakao/golajuma/auth/domain/service/ValidNicknameServiceTest.java, src/test/java/com/kakao/golajuma/auth/domain/token/TokenProviderTest.java, src/test/java/com/kakao/golajuma/auth/domain/token/TokenResolverTest.java
1. 회원가입 서비스 단위 테스트
2. 토큰 생성 / 토큰 정보 가져오기 단위 테스트
3. 이메일 / 닉네임 서비스 단위 테스트
closes (#이슈번호)
=> [Feat] 회원 가입 단위 테스트 작성

src/main/java/com/kakao/golajuma/auth/domain/service/LoginUserService.java, src/main/java/com/kakao/golajuma/common/support/respnose/MessageCode.java, src/main/java/com/kakao/golajuma/vote/web/controller/GetVoteDetailController.java, src/main/java/com/kakao/golajuma/vote/web/controller/GetVoteListController.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [SETTING] 개발 통합 

src/main/java/com/kakao/golajuma/vote/infra/entity/DecisionEntity.java, src/main/java/com/kakao/golajuma/vote/infra/repository/DecisionRepository.java
decision persistence layer 계층 추가했습니다.
1. decision entity 생성
2. decision repository 생성
빠진 필드 있는지, 테이블 명 올바른지 확인해주세요!
closes (#52 )
=> [Feat] decision persistence layer 계층 추가

src/main/java/com/kakao/golajuma/vote/domain/service/CreateVoteService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteDetailService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteListService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteService.java, src/main/java/com/kakao/golajuma/vote/infra/entity/OptionEntity.java, src/main/java/com/kakao/golajuma/vote/infra/entity/VoteEntity.java, src/main/java/com/kakao/golajuma/vote/infra/repository/OptionRepository.java, src/main/java/com/kakao/golajuma/vote/infra/repository/VoteRepository.java, src/main/java/com/kakao/golajuma/vote/util/OptionCheck.java, src/main/java/com/kakao/golajuma/vote/util/OptionValidator.java, src/main/java/com/kakao/golajuma/vote/web/dto/request/CreateVoteRequest.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/CountOptionDto.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/GetVoteDetailResponse.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/GetVoteListResponse.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/OptionDto.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/VoteDto.java, src/test/java/com/kakao/golajuma/vote/GetVoteListControllerTest.java
1. 투표 리스트 조회에서 공통 응답 부분을 다른 클래스로 추출했습니다.
2. custom validation에서 custom exception을 던지기로 수정했습니다.
3. ...
closes (#15)
=> [REFACTOR] 투표 리스트 조회 공통 응답 DTO 리팩토링

src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteService.java, src/main/java/com/kakao/golajuma/vote/util/OptionValidator.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/VoteDto.java, src/test/java/com/kakao/golajuma/vote/CreateVoteControllerTest.java, src/test/java/com/kakao/golajuma/vote/GetVoteDetailControllerTest.java, src/test/java/com/kakao/golajuma/vote/GetVoteListControllerTest.java
1. option validatior(custom) 에러 해결 
2. 통합 test json key 검증 추가 
3. 투표 리스트 및 상세 조회시 api category key 추가
closes (#이슈번호)
=> [10.11] 현수 작업 내용 

src/main/java/com/kakao/golajuma/vote/infra/entity/VoteEntity.java
1. 투표 Entity active 속성 제거 
closes (#이슈번호)
=> [FEAT] 투표 entity active 속성 제거

src/main/java/com/kakao/golajuma/vote/infra/entity/VoteEntity.java
=> [ 브랜치 방향 오류로 인해 Revert ] 투표 entity active 속성 제거

src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteListService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteService.java, src/main/java/com/kakao/golajuma/vote/infra/repository/VoteRepository.java, src/main/java/com/kakao/golajuma/vote/util/OptionValidator.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/VoteDto.java
1. 투표 entity active 속성을 없앤 후 투표 리스트 조회 쿼리를 현재 시각과 각 투표별 종료 시각을 비교하여 조회하는 방법으로 변경함
closes (#15)
=> [Refactor] 투표 리스트 조회 방식 변경 

src/main/java/com/kakao/golajuma/auth/domain/service/ReadUserProfileService.java, src/main/java/com/kakao/golajuma/auth/web/controller/UserProfileController.java, src/main/java/com/kakao/golajuma/auth/web/dto/response/UserProfileResponse.java, src/test/java/com/kakao/golajuma/mypage/ReadUserProfileTest.java
mypage 입장 첫 부분입니다.
1. mypage를 불러오고 nickName, email, image, 참여한 투표 수, 만든 투표 수를 반환하게 했습니다. 
closes (#61)
api test
=> [FEAT] mypage 구현

src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteDetailService.java, src/main/java/com/kakao/golajuma/vote/domain/service/ReadHotVoteService.java, src/main/java/com/kakao/golajuma/vote/infra/repository/HotVoteRepository.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/GetVoteListResponse.java
1. 투표 active 속성 제거에 따른 로직변경 
closes (#이슈번호)
=> [refactor] 투표 entity active 속성 제거에 따른 로직 변경

src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteListService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteService.java, src/main/java/com/kakao/golajuma/vote/infra/repository/VoteRepository.java, src/main/java/com/kakao/golajuma/vote/util/OptionValidator.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/VoteDto.java
Reverts Step3-kakao-tech-campus/Team11_BE#77
=> Revert "[refactor] push 오류 수정"

src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteListService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteService.java, src/main/java/com/kakao/golajuma/vote/infra/repository/VoteRepository.java, src/main/java/com/kakao/golajuma/vote/util/OptionValidator.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/VoteDto.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [refactor] push 오류 복구 작업 중 파일 복원

resources/local-develop-environment/mysql-init.d/01_create_table.sql, resources/local-develop-environment/mysql-init.d/02_insert_data.sql, src/main/java/com/kakao/golajuma/auth/infra/entity/AuthInfoEntity.java, src/main/java/com/kakao/golajuma/comment/infra/entity/CommentEntity.java, src/main/java/com/kakao/golajuma/vote/infra/entity/DecisionEntity.java, src/main/java/com/kakao/golajuma/vote/infra/entity/OptionEntity.java, src/main/java/com/kakao/golajuma/vote/infra/entity/VoteEntity.java
entity와 init data, create table을 수정했습니다 ./gradlew build 했을 때도 잘 됩니다
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [REFACTOR] table명 및 더미데이터 수정

Dockerfile, docker-compose.yml, resources/local-develop-environment/docker-compose.yml, src/main/resources/application-dev-mysql.yml, src/main/resources/application-dev-token.yml, src/main/resources/application-local-mysql.yml, src/main/resources/application-local-token.yml, src/main/resources/application.yml
dev 환경 세팅
1. dev 환경 세팅
2. dockerfile 생성
3. docker-compose 파일 생성
closes (#68)
크렘폴린에서
git pull 해오신 이후에
프로젝트 최상단에서 
1. ./gradlew clean
2. ./gradlew build
3. docker-compose up
해주세요!
=> [FEAT] dev 환경 세팅

src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteDetailService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteListService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteService.java, src/main/java/com/kakao/golajuma/vote/domain/service/ReadHotVoteService.java, src/main/java/com/kakao/golajuma/vote/domain/service/SearchVoteListService.java, src/main/java/com/kakao/golajuma/vote/infra/entity/Active.java, src/main/java/com/kakao/golajuma/vote/infra/entity/VoteEntity.java, src/main/java/com/kakao/golajuma/vote/infra/repository/VoteRepository.java, src/main/java/com/kakao/golajuma/vote/web/controller/GetVoteListController.java, src/main/java/com/kakao/golajuma/vote/web/controller/SearchVoteListController.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/GetVoteListResponse.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/SearchVoteListResponse.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/VoteDto.java, src/test/java/com/kakao/golajuma/vote/GetVoteListControllerTest.java, src/test/java/com/kakao/golajuma/vote/SearchVoteListControllerTest.java
1. 투표 리스트 검색 기능입니다 
closes (#이슈번호)
=> [feat] 투표 리스트 검색 기능 추가 

resources/local-develop-environment/mysql-init.d/02_insert_data.sql
1. 02_insert_data.sql 을 수정함
closes (#90 )
=> [REFACTOR] 더미데이터 시간변화

src/main/java/com/kakao/golajuma/comment/infra/entity/CommentEntity.java, src/main/java/com/kakao/golajuma/vote/domain/converter/DecisionEntityConverter.java, src/main/java/com/kakao/golajuma/vote/domain/exception/CompletionVoteException.java, src/main/java/com/kakao/golajuma/vote/domain/exception/ExistsDecisionException.java, src/main/java/com/kakao/golajuma/vote/domain/exception/NotFoundDecisionException.java, src/main/java/com/kakao/golajuma/vote/domain/service/DecisionService.java, src/main/java/com/kakao/golajuma/vote/infra/entity/OptionEntity.java, src/main/java/com/kakao/golajuma/vote/infra/entity/VoteEntity.java, src/main/java/com/kakao/golajuma/vote/infra/repository/DecisionRepository.java, src/main/java/com/kakao/golajuma/vote/infra/repository/OptionRepository.java, src/main/java/com/kakao/golajuma/vote/web/controller/DecisionController.java, src/main/java/com/kakao/golajuma/vote/web/dto/converter/DecisionResponseConverter.java, src/main/java/com/kakao/golajuma/vote/web/dto/converter/OptionResultConverter.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/DecisionResponse.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/OptionResult.java
투표 참여, 취소에 대해 구현했습니다.
테스트 코드 추가하겠습니다.
* 투표를 취소하면 댓글을 삭제한다
-> 이 부분은 아직 FE랑 논의가 안 끝나서 구현 안 했습니다!
closes (#67)
=> [FEAT] 투표 참여, 취소 구현

src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteDetailService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteListService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteService.java, src/main/java/com/kakao/golajuma/vote/domain/service/ReadHotVoteService.java, src/main/java/com/kakao/golajuma/vote/domain/service/SearchVoteListService.java, src/main/java/com/kakao/golajuma/vote/infra/entity/VoteEntity.java, src/main/java/com/kakao/golajuma/vote/infra/repository/VoteRepository.java, src/main/java/com/kakao/golajuma/vote/web/dto/request/CreateVoteRequest.java
1. 투표 진행 상태를 넘겨주는 메서드인자를 제거하였습니다
2. 투표 entity에서 투표 진행 상태를 확인하는 메서드를 추가하였습니다
closes (#101)
=> [Refactor] getVoteService 메서드 인자 리팩토링 

src/main/java/com/kakao/golajuma/vote/web/dto/response/VoteDto.java
1. ...
2. ...
3. ...
closed (#105 )
=> [Fix] 투표 조회 시 옵션 중복 문제 해결

.gitignore, Dockerfile, build.gradle, docker-compose.yml, k8s/configs/default.conf, k8s/deployment.yaml, k8s/ingress.yaml, k8s/kustomization.yaml, k8s/mariadb.yaml, k8s/mysql-init.d/00_init.sql, k8s/mysql-init.d/01_create_table.sql, k8s/mysql-init.d/02_insert_data.sql, resources/local-develop-environment/mysql-init.d/02_insert_data.sql, src/main/resources/application-dev-mysql.yml, src/main/resources/application-dev-token.yml
쿠버네티스 파일을 추가하고 여차하면 다른 플랫폼에도 할 수 있게 도커컴포즈, 도커파일 등을 살짝 변경했습니다.
1. 더미데이터의 시간이 지나 continue가 없는 오류를 수정했습니다.
2. 가이드북에 맞춰 k8s 셋팅을 했습니다.
3. 도커파일 내부에 폴더들을 copy하는 코드를 추가했습니다.
4. mariadb driver 의존성을 추가했습니다.
5. 도커컴포즈도 거의 바꿀건 없었지만 약간의 수정을 했습니다.
closes (#104 )
=> [REFACTOR] 배포를 위한 dev 설정 변경

src/main/java/com/kakao/golajuma/vote/domain/exception/CloseException.java, src/main/java/com/kakao/golajuma/vote/domain/service/CloseVoteService.java, src/main/java/com/kakao/golajuma/vote/domain/service/CreateVoteService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteListService.java, src/main/java/com/kakao/golajuma/vote/infra/entity/VoteEntity.java, src/main/java/com/kakao/golajuma/vote/web/controller/CloseVoteController.java, src/main/java/com/kakao/golajuma/vote/web/controller/GetVoteDetailController.java, src/main/java/com/kakao/golajuma/vote/web/controller/VoteController.java
투표 작성자는 진행중인 투표에 대해 마감할 수 있습니다.
1. voteEntity에 마감 기능을 추가하였습니다.
closes (#112)
=> [Feat] 투표 마감 기능 

src/main/java/com/kakao/golajuma/vote/domain/exception/SortException.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteListService.java, src/main/java/com/kakao/golajuma/vote/domain/service/Sort.java, src/main/java/com/kakao/golajuma/vote/infra/entity/Active.java, src/main/java/com/kakao/golajuma/vote/infra/entity/Category.java, src/test/java/com/kakao/golajuma/vote/GetVoteListControllerTest.java
투표 리스트 조회 방식 리팩토링입니다.
1. 먼저 메인페이지 or 완료된 페이지 요청인지 구별하고
2. 전체 카테고리 조회 or 세부 카테고리 조회인지 구별하고
3. 최신순 or 인기순 요청인지 구별하여 투표 리스트를 조회합니다 
전체적으로 중복되는 부분이 좀 있는 것 같고, 메소드 명을 어떻게 하면 더 좋을지 고민입니다.
closes (#114)
=> [Refactor] 투표 리스트 조회 방식 리팩토링 

src/main/java/com/kakao/golajuma/vote/domain/service/Sort.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/CountOptionDto.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/OptionDto.java, src/test/java/com/kakao/golajuma/vote/GetVoteDetailControllerTest.java
투표 조회 시 응답 dto 수정에 관한 pr입니다. 
1. optionDto, countOptionDto 필드명 api에 맞게 수정
closes (#118)
=> [Refactor] 투표 조회 dto 수정 

src/main/java/com/kakao/golajuma/vote/domain/service/SearchVoteListService.java, src/main/java/com/kakao/golajuma/vote/infra/repository/VoteRepository.java, src/main/java/com/kakao/golajuma/vote/web/controller/CloseVoteController.java, src/test/java/com/kakao/golajuma/vote/SearchVoteListControllerTest.java
투표 검색 기능 코드에 대한 리팩토링입니다. 
1. 검색 시 모든 카테고리를 조회하는 쿼리를 추가했습니다.
2. 검색 서비스 로직을 수정했습니다. 
closes (#121 )
=> [Refactor] 투표 검색 기능 리팩토링 

src/main/java/com/kakao/golajuma/vote/domain/service/SearchVoteListService.java, src/main/java/com/kakao/golajuma/vote/web/controller/CloseVoteController.java
1. 투표 dto 변환 시 스트림 적용 
closes (#121 )
=> [Refactor] 투표 dto 변환 시 스트림 적용 

resources/local-develop-environment/mysql-init.d/02_insert_data.sql, src/main/resources/application-dev-mysql.yml
use database 구문이 빠져 data가 삽입되지 않던 문제 해결
dev 환경변수의 이름을 잘못 설정한 문제 해결
1. 02_init_data.sql
- use golajuma; 추가
3. application-dev-mysql.yml
- username 환경변수 이름 변경
closes (#126 )
=> [FIX] local환경에서 데이터베이스가 설정돼있지 않던 문제 해결, dev환경변수 문제 해결

src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteListService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteService.java, src/main/java/com/kakao/golajuma/vote/infra/repository/VoteRepository.java, src/test/java/com/kakao/golajuma/vote/GetVoteListControllerTest.java
1. vote repo에 userId로 참여한 투표 리스트를 조회하는 쿼리를 추가하였습니다
2. decision repo에서 유저가 해당 옵션에 참여 여부를 확인할 수 있습니다 
closes (#128 )
=> [Refactor] 참여한 투표 리스트 조회 쿼리 추가 

src/main/java/com/kakao/golajuma/auth/domain/service/ReadUserProfileService.java, src/main/java/com/kakao/golajuma/auth/web/controller/UserProfileController.java, src/main/java/com/kakao/golajuma/auth/web/dto/response/UserProfileResponse.java, src/test/java/com/kakao/golajuma/auth/api/ReadUserProfileControllerTest.java, src/test/java/com/kakao/golajuma/auth/domain/service/ReadUserProfileServiceTest.java
마이페이지 부분 추가 및 리팩토링
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [REFACTOR] mypage 추가 + api, service테스트

src/main/java/com/kakao/golajuma/vote/infra/entity/OptionEntity.java, src/main/java/com/kakao/golajuma/vote/util/ImageUploader.java
1. 업로드 시 확장자 명을 추가하였습니다
2. 이미지가 없는 옵션 저장 시 null 값으로 저장합니다
closes (#)
=> [Refactor] 이미지 처리 수정 

src/main/java/com/kakao/golajuma/vote/web/dto/converter/DecisionResponseConverter.java
optionResultConverter null 오류 해결
1. final 키워드를 통해 생성자 주입을 시켜주었습니다.
왜 빠졌을까요..?
closes (#137 )
=> [FIX] 투표 취소 시 에러 null 오류 해결

src/main/java/com/kakao/golajuma/vote/util/ImageUploader.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/CountOptionDto.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/OptionDto.java
1. 이미지 업로드 경로 변경했습니다.
2. 이미지 인코딩 코드 추가하였습니다.
closes (#130 )
=> [Refactor] 이미지 업로드 경로 변경 및 인코딩 코드 추가 

src/main/java/com/kakao/golajuma/vote/util/ImageUploader.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/CountOptionDto.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/OptionDto.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [Refactor] 이미지 조회 확장자명 설정 

src/main/java/com/kakao/golajuma/vote/web/dto/response/CountOptionDto.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/OptionDto.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [Refactor] fe 요청에 따른 이미지 조회 주소값 응답 

src/main/java/com/kakao/golajuma/vote/util/ImageUploader.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/CountOptionDto.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/OptionDto.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [Refactor] 이미지 조회시 인코딩된 이미지 형식 추가

k8s/mysql-init.d/02_insert_data.sql, resources/local-develop-environment/mysql-init.d/02_insert_data.sql
이미지 더미데이터를 수정하였다.
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [FIX] 이미지 데이터 default >> null 변경

src/main/java/com/kakao/golajuma/auth/web/controller/UserProfileController.java, src/test/java/com/kakao/golajuma/auth/api/ReadUserProfileControllerTest.java
마이페이지의 url을 수정하였다.
1. ...
2. ...
3. ...
closes (#147 )
=> [FIX] mypage url 수정

src/main/java/com/kakao/golajuma/vote/infra/repository/VoteRepository.java, src/test/java/com/kakao/golajuma/vote/api/CreateVoteControllerTest.java, src/test/java/com/kakao/golajuma/vote/api/GetHotVoteListControllerTest.java, src/test/java/com/kakao/golajuma/vote/api/GetVoteDetailControllerTest.java, src/test/java/com/kakao/golajuma/vote/api/GetVoteListControllerTest.java, src/test/java/com/kakao/golajuma/vote/api/SearchVoteListControllerTest.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [Fix] 완료된 투표 조회 오류 해결 

src/main/java/com/kakao/golajuma/vote/domain/service/DecisionService.java, src/main/java/com/kakao/golajuma/vote/infra/entity/OptionEntity.java, src/main/java/com/kakao/golajuma/vote/util/OptionDivideUtil.java, src/main/java/com/kakao/golajuma/vote/web/controller/DecisionController.java, src/main/java/com/kakao/golajuma/vote/web/dto/converter/OptionResultConverter.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/CountOptionDto.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/OptionResult.java
option count 에러 문제 해결 합니다.
1. DecisionService 리팩터링
2. option count 감소할 때 -1로 되는 문제 해결
closes (#152 )
=> [FIX] option count 에러 문제 해결

src/main/java/com/kakao/golajuma/vote/domain/service/CloseVoteService.java, src/main/java/com/kakao/golajuma/vote/domain/service/CreateVoteService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteDetailService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteListService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteService.java, src/main/java/com/kakao/golajuma/vote/infra/entity/OptionEntity.java, src/main/java/com/kakao/golajuma/vote/infra/entity/VoteEntity.java, src/main/java/com/kakao/golajuma/vote/infra/repository/OptionRepository.java, src/main/java/com/kakao/golajuma/vote/infra/repository/VoteRepository.java, src/main/java/com/kakao/golajuma/vote/util/OptionDivideUtil.java, src/main/java/com/kakao/golajuma/vote/web/controller/GetVoteDetailController.java, src/main/java/com/kakao/golajuma/vote/web/dto/converter/DecisionResponseConverter.java, src/main/java/com/kakao/golajuma/vote/web/dto/converter/OptionResultConverter.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/CountOptionDto.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/CreateVoteResponse.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/GetVoteListResponse.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/OptionDto.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/VoteDto.java, src/test/java/com/kakao/golajuma/vote/api/GetVoteListControllerTest.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [chore ] long, int 타입 변경

src/main/java/com/kakao/golajuma/auth/domain/service/UpdateUserEmailService.java, src/main/java/com/kakao/golajuma/auth/domain/service/UpdateUserNickNameService.java, src/main/java/com/kakao/golajuma/auth/infra/entity/UserEntity.java, src/main/java/com/kakao/golajuma/auth/web/controller/UserProfileController.java, src/main/java/com/kakao/golajuma/auth/web/dto/request/UpdateUserEmailRequest.java, src/main/java/com/kakao/golajuma/auth/web/dto/request/UpdateUserNickNameRequest.java, src/main/java/com/kakao/golajuma/auth/web/dto/response/UpdateEmailResponse.java, src/main/java/com/kakao/golajuma/auth/web/dto/response/UpdateNickNameResponse.java, src/test/java/com/kakao/golajuma/auth/domain/service/UpdateUserEmailServiceTest.java, src/test/java/com/kakao/golajuma/auth/domain/service/UpdateUserNickNameServiceTest.java
업데이트 부분에 대한 API 구현. 겹칠만한 부분은 userEntity 이외에는 없습니다.
1. ...
2. ...
3. ...
closes (#148 )
=> [FEAT] 닉네임, 이메일 업데이트 구현

src/main/java/com/kakao/golajuma/vote/web/dto/request/CreateVoteRequest.java, src/test/java/com/kakao/golajuma/vote/api/CreateVoteControllerTest.java, src/test/java/com/kakao/golajuma/vote/api/GetVoteDetailControllerTest.java, src/test/java/com/kakao/golajuma/vote/api/SearchVoteListControllerTest.java, src/test/java/com/kakao/golajuma/vote/domain/service/CloseVoteServiceTest.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [Test] 투표 마감 서비스 테스트 코드 추가 

src/main/java/com/kakao/golajuma/vote/domain/exception/NotFoundVoteException.java, src/main/java/com/kakao/golajuma/vote/domain/service/DecisionService.java, src/main/java/com/kakao/golajuma/vote/web/controller/DecisionController.java, src/main/java/com/kakao/golajuma/vote/web/dto/converter/DecisionResponseConverter.java, src/main/java/com/kakao/golajuma/vote/web/dto/converter/OptionResultConverter.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/DecisionResponse.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/OptionResult.java
decision 업데이트를 구현합니다.
1. decision 업데이트
2. 기존 decision 중복 가능한 거 제거 -> 단일 선택만 가능
3. 서비스 전체적인 코드 리팩터링
closes (#163)
=> [FEAT] decision 업데이트 구현

src/main/java/com/kakao/golajuma/auth/domain/service/CreateTokenService.java, src/main/java/com/kakao/golajuma/auth/web/controller/LoginController.java, src/main/java/com/kakao/golajuma/auth/web/dto/converter/TokenConverter.java, src/main/java/com/kakao/golajuma/auth/web/dto/response/TokenResponse.java, src/main/resources/application-dev-token.yml, src/test/java/com/kakao/golajuma/auth/domain/service/ValidEmailServiceTest.java, src/test/java/com/kakao/golajuma/auth/domain/service/ValidNicknameServiceTest.java
토큰 관련하여 코드 변경하였습니다.
1. 토큰 만료 시간 늘림
2. 토큰 전달 위치 body로 변경
closes #164 
=> [FIX] 토큰 관련 변경

src/main/java/com/kakao/golajuma/auth/domain/service/ReissueService.java, src/main/java/com/kakao/golajuma/auth/web/controller/AuthController.java, src/main/java/com/kakao/golajuma/auth/web/support/CookieExtractor.java
엑세스 토큰 재발급 기능
1. 리프레시 쿠키 추출
2. 엑세스, 리프레시 재발급
closes #31
=> [FEAT] 엑세스 토큰 재발급 기능

src/main/java/com/kakao/golajuma/auth/web/dto/request/UpdateUserEmailRequest.java, src/main/java/com/kakao/golajuma/auth/web/dto/request/UpdateUserNickNameRequest.java
빈 생성자 만들기
1. ...
2. ...
3. ...
closes (#167 )
=> [FIX] 이메일,닉네임 업데이트 오류 해결 PR

k8s/mysql-init.d/01_create_table.sql, resources/local-develop-environment/mysql-init.d/01_create_table.sql
count의 타입을 Long에서 int로 변환했기 때문에 싱크를 맞춤
1. ...
2. ...
3. ...
closes (#166 )
=> [FIX] db 타입 bigint > integer

src/main/java/com/kakao/golajuma/auth/domain/service/UpdateUserNickNameService.java, src/main/java/com/kakao/golajuma/auth/web/dto/request/UpdateUserNickNameRequest.java, src/test/java/com/kakao/golajuma/auth/domain/service/UpdateUserEmailServiceTest.java, src/test/java/com/kakao/golajuma/auth/domain/service/UpdateUserNickNameServiceTest.java
생성자 부분 변경하면서 생긴 오류 해결
1. ...
2. ...
3. ...
closes (#171 )
=> [FIX] email, nickname update 테스트 오류 해결

src/main/java/com/kakao/golajuma/auth/web/interceptor/AuthInterceptor.java, src/main/java/com/kakao/golajuma/auth/web/support/AnonymousAvailable.java, src/main/java/com/kakao/golajuma/auth/web/support/AuthenticationPrincipalArgumentResolver.java, src/main/java/com/kakao/golajuma/auth/web/support/LoginRequired.java, src/main/java/com/kakao/golajuma/config/WebMvcConfig.java
비로그인자 접근 가능 기능 추가했습니다.
1. AnonymousAvailable이 추가되었습니다.
2. 해당 어노테이션을 메서드에 추가하면, 해당 api는 비로그인자도 접근할 수 있음을 나타냅니다.
3. 만약,` @AnonymousAvailable`이 있는 api 를 호출한 사용자가 
* 비로그인자인 경우 : 0L반환
* 로그인자인 경우 : 사용자 Id 반환 합니다.
아래는 실제 controller 단의 사용 예시 입니다.
closes #115
=> [FEAT] 비로그인자 접근 가능 기능 추가

src/main/java/com/kakao/golajuma/vote/domain/service/CreateVoteService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteListService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteService.java, src/test/java/com/kakao/golajuma/vote/domain/service/CreateVoteServiceTest.java, src/test/java/com/kakao/golajuma/vote/domain/service/GetVoteServiceTest.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [Test] 테스트 코드 추가 

src/main/java/com/kakao/golajuma/vote/web/controller/GetVoteDetailController.java, src/main/java/com/kakao/golajuma/vote/web/controller/GetVoteListController.java, src/main/java/com/kakao/golajuma/vote/web/controller/SearchVoteListController.java
1. ...
2. ...
3. ...
closes (#175 )
=> [Refactor] 비로그인 사용자 어노테이션 적용 

src/main/java/com/kakao/golajuma/comment/domain/service/GetCommentListService.java, src/main/java/com/kakao/golajuma/comment/web/controller/GetCommentListController.java, src/main/java/com/kakao/golajuma/vote/web/controller/GetHotVoteListController.java
이번에 새로 완성된 비로그인 어노테이션을 적용했습니다.
1. ...
2. ...
3. ...
closes (#177 )
유닛테스트, 통합테스트
=> [REFACTOR] 핫게, 댓글 비로그인 어노테이션 적용

src/main/java/com/kakao/golajuma/vote/domain/service/DecisionService.java
=> [FIX] 투표 생성 에러 해결

src/main/java/com/kakao/golajuma/auth/domain/exception/AuthorizationException.java, src/main/java/com/kakao/golajuma/auth/domain/exception/CookieException.java, src/main/java/com/kakao/golajuma/auth/domain/token/TokenResolver.java, src/main/java/com/kakao/golajuma/auth/domain/token/TokenValidator.java, src/main/java/com/kakao/golajuma/auth/web/support/CookieExtractor.java, src/main/resources/application-dev-token.yml
인증 status code 재정의 하였습니다.
1. status code (401,403)으로 변경
2. 만료 시간 재설정
close #181
=> [FIX] 인증 status code 재정의

src/main/resources/application-dev-token.yml
dev token 만료 시간 재설정
close #181 
=> [FIX] dev token 만료 시간 재설정

src/main/java/com/kakao/golajuma/vote/domain/service/CloseVoteService.java, src/main/java/com/kakao/golajuma/vote/web/controller/CloseVoteController.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [Fix] 투표 마감 오류 해결 

src/main/java/com/kakao/golajuma/vote/domain/service/CloseVoteService.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [fix] readOnly 제거

src/test/java/com/kakao/golajuma/vote/api/CloseVoteControllerTest.java, src/test/java/com/kakao/golajuma/vote/api/GetVoteListControllerTest.java, src/test/java/com/kakao/golajuma/vote/domain/service/GetVoteListServiceTest.java, src/test/java/com/kakao/golajuma/vote/domain/service/SearchVoteListServiceTest.java
1. 투표 리스트 검색 단위 테스트 추가
2. 투표 리스트 조회 단위 테스트 추가
3. 투표 리스트 조회 테스트 케이스 추가
4. 투표 마감 통합 테스트 추가
closes (#144 )
=> [Test] 투표 테스트 추가 (투표 리스트 조회 단위 테스트 추가, 투표 마감, 리스트 조회 통합 테스트 추가)

src/main/java/com/kakao/golajuma/auth/domain/service/UpdateUserEmailService.java, src/main/java/com/kakao/golajuma/auth/domain/service/UpdateUserNickNameService.java, src/main/java/com/kakao/golajuma/auth/web/dto/request/UpdateUserEmailRequest.java, src/main/java/com/kakao/golajuma/auth/web/dto/request/UpdateUserNickNameRequest.java, src/main/java/com/kakao/golajuma/auth/web/dto/response/UpdateEmailResponse.java, src/main/java/com/kakao/golajuma/auth/web/dto/response/UpdateNickNameResponse.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetHotVoteListService.java, src/main/java/com/kakao/golajuma/vote/web/controller/GetHotVoteListController.java, src/test/java/com/kakao/golajuma/auth/api/UpdateUserEmailApiTest.java, src/test/java/com/kakao/golajuma/auth/api/UpdateUserNickNameApiTest.java, src/test/java/com/kakao/golajuma/auth/domain/service/UpdateUserEmailServiceTest.java, src/test/java/com/kakao/golajuma/auth/domain/service/UpdateUserNickNameServiceTest.java, src/test/java/com/kakao/golajuma/vote/api/GetHotVoteListControllerTest.java, src/test/java/com/kakao/golajuma/vote/domain/service/GetHotVoteListServiceTest.java, src/test/java/com/kakao/golajuma/vote/repository/GetHotVoteListRepositoryTest.java
핫게시판의 전반적인 부분을 다듬었습니다.
닉네임, 이메일 업데이트에 중복검사 서비스를 포함시켰고 테스트를 추가했습니다.
각 부분들의 쓰지 않는 코드들을 제거했습니다.
각각 커버리지 100%
1. ...
2. ...
3. ...
closes (#184 )
=> [REFACTOR] 이메일,닉네임 변경 + 핫게시판 리팩토링

src/main/java/com/kakao/golajuma/vote/infra/repository/VoteRepository.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [chore] 참여한 투표 리스트 조회 시 정렬방식 추가

src/main/java/com/kakao/golajuma/vote/domain/service/CreateVoteService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetAskedVotesService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetParticipatedVotesService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteDetailService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVotesService.java, src/main/java/com/kakao/golajuma/vote/domain/service/SearchVotesService.java, src/main/java/com/kakao/golajuma/vote/infra/entity/OptionEntity.java, src/main/java/com/kakao/golajuma/vote/infra/entity/VoteEntity.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/CountOptionDto.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/CreateVoteResponse.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/GetVoteDetailResponse.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/GetVotesResponse.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/OptionDto.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/SearchVotesResponse.java, src/main/java/com/kakao/golajuma/vote/web/dto/response/VoteDto.java, src/test/java/com/kakao/golajuma/vote/api/CreateVoteControllerTest.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [Refactor] 메소드명 및 필드명 수정 

src/main/java/com/kakao/golajuma/comment/infra/repository/CommentRepository.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [REFACTOR] 댓글 개수 deleted=false 설정

src/main/java/com/kakao/golajuma/vote/util/ImageUploader.java, src/main/resources/application-dev-image.yml, src/main/resources/application-local-image.yml, src/main/resources/application.yml
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [Refactor] image upload path 환경변수 설정

README.md
1. ...
2. ...
3. ...
closes (#208 )
=> docs : readme 작성

src/main/java/com/kakao/golajuma/vote/domain/service/CloseVoteService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetAskedVotesService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetParticipatedVotesService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteDetailService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteService.java, src/main/java/com/kakao/golajuma/vote/domain/service/GetVotesService.java, src/main/java/com/kakao/golajuma/vote/domain/service/SearchVotesService.java, src/main/java/com/kakao/golajuma/vote/util/ImageUploader.java, src/main/java/com/kakao/golajuma/vote/web/controller/CloseVoteController.java, src/main/java/com/kakao/golajuma/vote/web/controller/CreateVoteController.java, src/main/java/com/kakao/golajuma/vote/web/controller/GetVotesController.java, src/main/java/com/kakao/golajuma/vote/web/controller/SearchVotesController.java, src/main/java/com/kakao/golajuma/vote/web/dto/request/CreateVoteRequest.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [Refactor] 주석 제거 

src/main/java/com/kakao/golajuma/comment/domain/service/DeleteAllCommentByVoteService.java, src/main/java/com/kakao/golajuma/comment/infra/repository/CommentRepository.java, src/main/java/com/kakao/golajuma/vote/domain/event/DeleteAllCommentEventHandler.java, src/main/java/com/kakao/golajuma/vote/domain/event/DeletedDecisionEvent.java, src/main/java/com/kakao/golajuma/vote/domain/service/DeleteDecisionService.java
decision 삭제 시 댓글 삭제 구현
close #106 
=> [FEAT] decision 삭제 시 댓글 삭제 구현

src/main/java/com/kakao/golajuma/vote/util/ImageUploader.java
1. ...
2. ...
3. ...
closes (#이슈번호)
=> [REFACTOR] image upload 용량 제한 완화

src/main/java/com/kakao/golajuma/auth/web/dto/request/LoginUserRequest.java, src/main/java/com/kakao/golajuma/auth/web/dto/request/SaveUserRequest.java, src/main/java/com/kakao/golajuma/auth/web/dto/request/UpdateUserEmailRequest.java, src/main/java/com/kakao/golajuma/auth/web/dto/request/UpdateUserNickNameRequest.java, src/main/java/com/kakao/golajuma/auth/web/dto/request/ValidEmailRequest.java, src/main/java/com/kakao/golajuma/auth/web/dto/request/ValidExceptionMessage.java, src/main/java/com/kakao/golajuma/auth/web/dto/request/ValidNicknameRequest.java, src/test/java/com/kakao/golajuma/auth/domain/service/CreateTokenServiceTest.java, src/test/java/com/kakao/golajuma/auth/domain/service/LoginUserServiceTest.java, src/test/java/com/kakao/golajuma/auth/domain/service/ReissueServiceTest.java
=> [FEAT] 인증 테스트코드 추가

src/main/resources/application-dev-token.yml, src/test/java/com/kakao/golajuma/vote/domain/service/CreateDecisionServiceTest.java
투표 생성 실패 테스트 
1.  투표 생성 실패 테스트 
2. 토큰 만료 시간 변경
closes (#이슈번호)
=> [TEST] 투표 생성 실패 테스트 코드
